{% set name = "distgen" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4056ef72040bf7d980d202bb5eabde6a7acdb3f0cc5d9d99857793b4812a5995

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - matplotlib-base
    - numpy
    - pint
    - scipy
    - openpmd-beamphysics
    - pyyaml

test:
  imports:
    - distgen

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Particle distribution generator
  description: |
    Particle distribution generator

extra:
  recipe-maintainers:
    - ColwynGulliford
