{% set name = "distgen" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d7284cc5819abc229015547e1de1a4fcd6f822c0d38f6deb2247a4286e59af85

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - h5py
    - matplotlib-base
    - numpy
    - pint
    - scipy
    - openpmd-beamphysics
    - pyyaml
    - lume-base
    - pydicom

test:
  imports:
    - distgen

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Particle distribution generator
  description: |
    Particle distribution generator

extra:
  recipe-maintainers:
    - ColwynGulliford
