{% set name = "distgen" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b726fe8fa5cfef6105e5bab77f21d74f91033e3f25c78ece6c5cc32104f6094f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - setuptools
  run:
    - python >=3.9,<3.13
    - h5py
    - matplotlib-base
    - numpy
    - pint
    - scipy
    - openpmd-beamphysics
    - pyyaml
    - lume-base
    - pydicom

test:
  imports:
    - distgen

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Particle distribution generator
  description: |
    Particle distribution generator

extra:
  recipe-maintainers:
    - ColwynGulliford
